### ISSUE TITLE
Rename "fflib/v1" to "fflib.v2".

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#100]
By using the trick that golang discards everything after a dot in package path.

This means that if we name the folder "fflib.v1" (or v2), the import path would look like this:

``` Go
import "github.com/pquerna/ffjson/fflib.v1"
```

(Without needing to alias it)

And we could call the package "fflib" instead of "v1".

Does that make sense?

**Comment by pquerna** [comment]
I'm +1 for when we need to have a v2, but I'd like to keep v1 API compat for as long as reasonable.

**Comment by klauspost** [comment]
Yes - what is your opinion on *adding* things to a current version?

The reason only reason I could see for bumping when adding things are if people are using their own vendoring. And even that would just require an upstream update to get the features they need.

So I don't personally see a good reason to bumping because of additions, but I just want to be sure if you (and maybe other people seeing this) agree.

**Comment by pquerna** [comment]
yeah, I don't think we should bump for additions, just for a API breakage, or if we go through a bigger rewrite of the generator code which means the currently exported functions are not used at all.

**Comment by GeertJohan** [comment]
What about gopkg.in?
I think it's a nice service providing versioned git repo links.
e.g.: gopkg.in/github.com/username/repo.v2 would point to the last `v2[.x[.y]]` branch or tag on that repo.
You can still use master to develop, and tag to `v2.x.y` to "release" a new version.
