### ISSUE TITLE
ffjson should be the only package you need to import

### ISSUE THREAD

**Issue by pquerna** [pquerna/ffjson#106]
`github.com/pquerna/ffjson/ffjson` should be the only package we tell users to import.
- [x] Need to add a `ffjson.Pool()` which just calls `fflib.Pool`. PR #109 
- [x] Need to update README.md. Done in master
- [x] Add godoc links for it
- [x] Add a reusable Buffer to ffjson as per tip number 3.

**Comment by klauspost** [comment]
Well spotted. I am going home for today, have a nice day!

**Comment by klauspost** [comment]
the encoder is done - would it make sense to have a Decoder similar to `encoding/json`?

**Comment by pquerna** [comment]
+1 to decoder

**Comment by klauspost** [comment]
PR #129
