### ISSUE TITLE
float64 aliases generate broken code

### ISSUE THREAD

**Issue by richleigh** [pquerna/ffjson#107]
Example: fftest.go
```
package fftest

type Price float64

type Item struct {
	Description string
	Cost        Price
}
```
`go build` shows no errors. After running `ffjson fftest.go`, `go build` reports `./fftest_ffjson.go:31: cannot use mj.Cost (type Price) as type float64 in argument to strconv.AppendFloat`

Seems like the problem is in encoder.go:185. `float32` aliases work because of the cast to `float64` on line 182, and applying the same cast on 185 fixes the issue. Ints and strings also always go through a cast masking the issue when using types which alias them.

**Comment by klauspost** [comment]
Should be fixed now. Did find a more complex issue #108, and even a bug in the golang encoding/json when I added tests for renamed types.
