### ISSUE TITLE
Use String() method when possible on structs?

### ISSUE THREAD

**Issue by jgoodall** [pquerna/ffjson#123]
Is it possible to have ffjson use the `String()` method on objects that have it rather than encoding it? I have a `net.IP` object, and want to have Marshal create a string instead of base64 encoding the bytes.

Is that possible?

**Comment by pquerna** [comment]
Well, overall we want to preserve the same behaviors as the stdlib `encoding/json` whenever possible, so the "right' way to do this is to type-alias `net.IP` and add a MarshalJSON / UnmarshalJSON specialization for it.....

**Comment by klauspost** [comment]
I also cannot see how we can make that work reliably. As Paul writes, the best solution would be to 

To make it as fast as possible, you can of course implement your own marshal:

```Go
type MyIP net.IP

func (mj *MyIP) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
    buf.WriteString(`"`+mj.String()+`"`)
    return nil
}
``
