### ISSUE TITLE
go tool: no such tool "6a" for appengine project.

### ISSUE THREAD

**Issue by ceram1** [pquerna/ffjson#142]
`goapp` does not have 6a.
Can I use go tool 6a with go-cmd=goapp?

```
$ go version
go version go1.4.2 linux/amd64

$ go tool
6a
6c
6g
6l
addr2line
cgo
cover
dist
fix
nm
objdump
pack
pprof
tour
vet
yacc

$ goapp version
go version go1.4.2 (appengine-1.9.21) linux/amd64

$ goapp tool
6g
6l
pack
```

**Comment by pquerna** [comment]
hmm. not sure here, we only invoke `go` or the value of `go-cmd`.... never 6a directly.   I'll have to setup app-engine to see whats going on unless you have any ideas.

**Comment by ceram1** [comment]
Hmm.. Now I found that I can't install ffjson with `goapp`
```
$ goapp get -u github.com/pquerna/ffjson
go tool: no such tool "6a"
```

**Comment by pquerna** [comment]
thank you for the report and PR!

**Comment by Abdullah114** [comment]
@ceram1 did you face this problem for btcd or btcec?
how did you fix it?

**Comment by ceram1** [comment]
I didn't use any bitcoin projects.
Just googled it, then found a [gae issue](https://code.google.com/p/googleappengine/issues/detail?id=11281) and a patch(https://github.com/btcsuite/fastsha256/pull/2)
