### ISSUE TITLE
Support for json.Number

### ISSUE THREAD

**Issue by vinceprignano** [pquerna/ffjson#153]
Using the standard library json package and creating a new decoder you can keep the numbers as strings and have them as `json.Number`, I've noticed that ffjson doesn't respect that when enabling the option.

**Comment by vinceprignano** [comment]
@pquerna any view/updates on this one? :) I would be happy to help

**Comment by pquerna** [comment]
@vinceprignano yes, this is a good thing to fix.

**Comment by vinceprignano** [comment]
Thank you!
