### ISSUE TITLE
When ffjson is vendored with GO15VENDOREXPERIMENT, go generate doesn't work.

### ISSUE THREAD

**Issue by dimfeld** [pquerna/ffjson#163]
In one of my projects I have the ffjson package vendored using the GO15VENDOREXPERIMENT method so I can use `ffjson.Encoder`. When I run `go generate`, I get the following error:

```
/var/folders/w0/w_fx2xms6jsf79zwcqq3tbvh0000gn/T/ffjson-inception288838651.go:14: 
cannot use writer.FFJSONExpose() (type 
[]"bitbucket.org/freshmedicalleads/datafuse/vendor/github.com/pquerna/ffjson/shared".InceptionType) 
as type []"github.com/pquerna/ffjson/shared".InceptionType in argument to i.AddMany
```

As you can see, it's trying to use the vendored ffjson package but the executable is expecting the non-vendored version. I assume this is because the inception file is running out of the temp directory instead of the project's source directory; not sure though.

I worked around this for now by just running `GO15VENDOREXPERIMENT=0 go generate`, which I think may stop working once Go 1.7 comes out.  I also tried updating the import path in the temporary file to reference the vendored ffjson instead, and that appeared to work. I don't know if you can detect the presence of a vendored package when automatically building the source though.

The source file I'm using with ffjson as well as my edited temp file that builds successfully is here: https://gist.github.com/dimfeld/10e2d19144a8f9cced83

FWIW this wasn't a problem when I used `gb`. I suppose its GOPATH trickery avoids this problem.

**Comment by pquerna** [comment]
right, when GOPATH is edited, we keep it there... Hmm. I suspect we can make a temp directory in the source directory, and the `vendor` path will be used.

**Comment by dimfeld** [comment]
I just tried doing that manually, and it seems to work :)
