### ISSUE TITLE
Generate lint-free code

### ISSUE THREAD

**Issue by janisz** [pquerna/ffjson#169]
Generated code should pass [golint](https://github.com/golang/lint) checks. I think it'll be easy fix, issues I encourage are:
- don't use underscores in Go names
- exported method should have comment or be unexported
- should drop = nil from declaration of var err; it is the zero value

**Comment by cblomart** [comment]
I do check golint on my project... and now ffjson breaks the build.

**Comment by cblomart** [comment]
Proposed a pull request #220

**Comment by ammario** [comment]
Lint fix has been merged. This issue should be closed. Thank you @cblomart
