### ISSUE TITLE
NewLine character were is shouldn't be

### ISSUE THREAD

**Issue by matijavizintin** [pquerna/ffjson#173]
This example shows that a **new line character** is introduced after a map[whatever]interface{}. 

CODE:

    
    //go:generate ffjson $GOFILE
    package playground

    type Struct struct {
	    Map    map[string]interface{} `json:"map"`
	    String string                 `json:"string"`
    }

    
    package main

    import (
	    "fmt"
	    "playground"
	    "github.com/pquerna/ffjson/ffjson"
    )

    func main() {
	    s := playground.Struct{
		    Map: map[string]interface{}{"key": "val", "key1": 1},
		    String: "dummy",
	    }
	    bytes, _ := ffjson.Marshal(&s)
	    fmt.Println(string(bytes))
    }

And the result of this code is:
 
```
{"map":{"key":"val","key1":1}
,"string":"dummy"}

```
instead of 

` {"map":{"key":"val","key1":1},"string":"dummy"}
`

This JSON is technically valid but is really annoying this newline char if you put jsons in files and you rely on that every line is a whole json.

**Comment by pquerna** [comment]
This is because we are miss-using `Encoder.Encode`.  It is documented as adding a newline, but we didn't expect this to happen.  not sure how to best fix this.

https://golang.org/pkg/encoding/json/#Encoder.Encode
