### ISSUE TITLE
How to parse [{"a": "1"}] ?

### ISSUE THREAD

**Issue by bloodynumen** [pquerna/ffjson#200]
How to parse [{"a": "1"}] ? Thx~

**Comment by erikdubbelboer** [comment]
For example like this. But I don't see how this is relevant to this package so I suggest you close the issue.

```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	src := `[{"a": "1"}]`

	var x []struct {
		A string `json:"a"`
	}

	if err := json.Unmarshal([]byte(src), &x); err != nil {
		panic(err)
	}

	fmt.Printf("%v", x)
}
```

**Comment by bloodynumen** [comment]
Sorry, perhaps my description is not accurate

Can I parse json such as   `[{"a": "1"}]`  with ffjson , not use "encoding/json".

Because ffjson is faster~

**Comment by erikdubbelboer** [comment]
Like the documentation states it transparently optimizes things already once you generated the _ffjson files: https://github.com/pquerna/ffjson#tip-1-use-ffjsonmarshal--ffjsonunmarshal

**Comment by bloodynumen** [comment]
Thx~ But how to define the struct for `[{"a": "1"}]` ?

My temporary solution is :
`
type A struct {
    A string `json:"a"`
}

type Wapper struct {
    Data []A
}
`
`
str := `{"Data":`  + `[{"a": "1"}]` + `}`
......
`

**Comment by erikdubbelboer** [comment]
If you define a struct `A` like that you can just do:
```go
var a []A // An array of A's.
json.Unmarshal(str, &a)
```

Again, this is nothing special so I suggest you read the documentation here: https://golang.org/pkg/encoding/json/#Unmarshal

**Comment by bloodynumen** [comment]
Thank you very much~ 
I'm sorry for my carelessness and poor english...
