### ISSUE TITLE
ffjson generated file fails for embedded anonymous pointer field

### ISSUE THREAD

**Issue by ugorji** [pquerna/ffjson#208]
See the type below:

type AnonInTestStruc struct {
	AS        string
}

type AnonInTestStrucIntf struct {
	Islice []interface{}
}

type TestStruc struct {
	S    string
	AnonInTestStruc
	*AnonInTestStrucIntf
}

func main() {
  var x TestStruc
  x.AS = "AS"
  // encode it - it will throw exception like below
}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9355a5]

The error is because the AnonInTestStrucIntf is not initialized in the generated code.

**Comment by klauspost** [comment]
Duplicate of #112

**Comment by ugorji** [comment]
Closing as duplicate
