### ISSUE TITLE
Go 1.11 modules support

### ISSUE THREAD

**Issue by jrmarkle** [pquerna/ffjson#246]
With [go 1.11 modules](https://github.com/golang/go/wiki/Modules) source code may be located outside of GOPATH.

When I tried migrating a project to use go.mod and build outside of the GOPATH, ffjson is failing with "Could not find source directory" errors. I see that the latest commit pre-dates the release of go 1.11.

Does ffjson support modules? (And if not, are there any plans?)

**Comment by andersfylling** [comment]
Any news on this?

**Comment by azzuwan** [comment]
Is this the same reason for this error?
![image](https://user-images.githubusercontent.com/816052/54740434-5b75de00-4bf6-11e9-8e4c-31f532ff14da.png)
