### ISSUE TITLE
Proposal: Add command line parameter to only create en/de-coder.

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#43]
For some structures/files I know I will only need the encoder for instance. It would be nice to be able to disable one or the other.

It could also be a struct comment directive similar to //ffjson:skip - maybe //ffjson:encoderOnly and //ffjson:decoderOnly - 

Preferably I would have both options (both as command-line and struct comment), but one would also be nice.

**Comment by pquerna** [comment]
+1 to the idea, would be nice to unify the command line flags and `ffjson:skip` comments so they make sense all together.
