### ISSUE TITLE
Recover in makeSlice?

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#62]
Looking at the benchmark times, I noticed roughly 0.7% was spent in a defer in makeSlice. What is the reason for this defer. I am not sure if catching a panic, and sending a new one solves much?

```Go
// makeSlice allocates a slice of size n. If the allocation fails, it panics
// with ErrTooLarge.
func makeSlice(n int) []byte {
	// If the make fails, give a known error.
	defer func() {
		if recover() != nil {
			panic(ErrTooLarge)
		}
	}()
	return make([]byte, n)
}
```

**Comment by pquerna** [comment]
Yes, `makeSlice` is from the upstream `bytes.Buffer` code.  I've thought about removing the defer/panic catching, but there were easier ways to get performance elsewhere.  As long as we are OK with... lets just say multi-gigabyte `ffjson` runs failing with a harder to debug error... then yes, we can remove it.
