### ISSUE TITLE
[]byte and []uint8 decoding fails

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#65]
Struct:
```Go
type ATbyte struct {
	X []byte
}
```
Fails with this content:
```Json
{"X":"VcELoXc4nIW9KPnUoVg="}
```

Message: "cannot unmarshal tok:string into Go value for  offset=27 line=1 char=27"

**Comment by pquerna** [comment]
encoding/json does do base64 decode of these fields here:
http://golang.org/src/encoding/json/decode.go?s=2340:2388#L740

(not documented)
