### ISSUE TITLE
Decide how to handle golang asymmetric string tags

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#79]
While writing tests I encountered this issue:

https://github.com/golang/go/issues/9812

Short story, golang removes quotes if string tag is set, but it is not added on encode, leading to encoded content that cannot be unmarshaled by itself.

My proposal to handling this would be to generate code that does the same, but prints a warning to the user that they are playing with fire (ie their code will only work one way)

**Comment by pquerna** [comment]
I think we will want to match upstream behavior, though i don't love it.
