### ISSUE TITLE
Support "string" tag in decoder

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#80]
Have I broken something, or is "string" unsupported in the decoder:

```Go
func TestForceStringTaggedDecoder(t *testing.T) {
	testCycle(t, &TstringTagged{}, &XstringTagged{})
	testCycle(t, &TintTagged{}, &XintTagged{})
	testCycle(t, &TboolTagged{}, &XboolTagged{})
}
```
Adding this test, it seems like the string tag is ignored, and the quotes aren't removed. Is this correct?

**Comment by klauspost** [comment]
(marking as bug, since it is needed for `encoding/json` compatibility.

**Comment by corsc** [comment]
I would like to use this feature as well, is there anything that can be done to complete this?

**Comment by memoleaf** [comment]
Sorry for the multiple commits. Having some trouble with the formatting.

The patch should resolve this issue. Please comment.
