### ISSUE TITLE
Decoder should not be case sensitive

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#84]
This is a rather big one. It seems like golang doesn't care about case when looking for matching fields.

Test:
```Go
func TestCaseDiffentUnmarshal(t *testing.T) {
	base := Record{}
	ff := FFRecord{}

	err := json.Unmarshal([]byte(`{"ID": 123213, "originid": 22, "Meth": "GET"}`), &base)
	if err != nil {
		t.Fatalf("UnmarshalJSON: %v", err)
	}

	err = json.Unmarshal([]byte(`{"ID": 123213, "originid": 22, "Meth": "GET"}`), &ff)
	if err != nil {
		t.Fatalf("UnmarshalJSON: %v", err)
	}
	require.Equal(t, base, ff, "json.Unmarshal of Record")
}
```

Golang picks up the content of the fields, even though the case mismatches. ffjson should do the same.

**Comment by pquerna** [comment]
Quoting from the docs:

```markdown
How does Unmarshal identify the fields in which to store the decoded data? For a given JSON key "Foo", Unmarshal will look through the destination struct's fields to find (in order of preference):

- An exported field with a tag of "Foo" (see the Go spec for more on struct tags),
- An exported field named "Foo", or
- An exported field named "FOO" or "FoO" or some other case-insensitive match of "Foo".
```

From the docs:

```
To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match.
```

I think the easy way out here would be to have a second set of key matches after the first, that lowercases both sides and builds a similiar switch statement as to what we have today.

**Comment by klauspost** [comment]
Sounds like a good approach.

I *think* I read a bug report that the documentation wasn't accurate, and that there were some cases where case insensitive match was in reality preferred over a tag match, so we might need to take special care.

**Comment by pquerna** [comment]
tracing down how this seems to work in `encoding/json`:

1) fields in get their folding function assigned from their named bytes here: https://github.com/golang/go/blob/HEAD/src/encoding/json/encode.go#L936-L953

2) `foldFunc` returns a function depending on how much-unicode and other fun stuff is in the field: https://github.com/golang/go/blob/HEAD/src/encoding/json/fold.go#L18-L33

3) Finally the `equalFolds` function is used while decoding the Key here: https://github.com/golang/go/blob/HEAD/src/encoding/json/decode.go#L562-L571

So, you'll notice that in the loop over the fields, it doesn't `break` on a case-based match -- it keeps looping, so the last case-match wins if there is never any exact matches.

**Comment by pquerna** [comment]
Support is merged in, though we could use some optimizations on it.
