### ISSUE TITLE
Travis-CI build failing 

### ISSUE THREAD

**Issue by pquerna** [pquerna/ffjson#85]
After committing 5c410f733010199d66597f0c8ff110a62846cf50 travis-ci has been failing the build.

For example:
https://travis-ci.org/pquerna/ffjson/jobs/50264700

I'm not able to reproduce the test failures locally. (OSX and Linux)

**Comment by pquerna** [comment]
this might be related to the upstream change here in testify:

https://github.com/stretchr/testify/pull/128

not quite sure yet.

**Comment by klauspost** [comment]
Could very well be the case. However, give me 5 minutes, and I think I can actually fix it.

**Comment by klauspost** [comment]
(How on earth they can change that in a *testing* framework is beyond me).

**Comment by pquerna** [comment]
https://github.com/stretchr/testify/issues/129

**Comment by klauspost** [comment]
ok - my initial idea didn't work, but simply adding the code they removed fixes it - it is reflect.DeepEqual we want.
